### ISSUE TITLE
ExtDeprecationWarning on flask >= 0.11

### ISSUE THREAD

**Issue by lixxu** [thadeusb/flask-cache#140]
flask 0.11 will issue a ExtDeprecationWarning for `flask.ext.cache` format.

```
C:\python27\lib\site-packages\flask\exthook.py:71: ExtDeprecationWarning: Importing flask.ext.cache is deprecated, use flask_cache instead.
```

**Comment by hitigon** [comment]
#139 has fixed this issue. but seems nobody is maintaining this project anymore, last commit is almost two years ago.

**Comment by lixxu** [comment]
duplicate with https://github.com/thadeusb/flask-cache/pull/139
