### ISSUE TITLE
memoize can't deal the magic arguments

### ISSUE THREAD

**Issue by ponytailer** [thadeusb/flask-cache#177]
memoize_make_cache_key  can't deal the magic arguments.

```
@cache.memoize(timeout=3)
def test(**kw):
    return 1
```

**Comment by dengshaochun** [comment]
I had the same problem

**Comment by dengshaochun** [comment]
i modify part of the code, make memoize support function only with magic arguments.
#180

**Comment by ponytailer** [comment]
If the same value has the different key in the kwargs， your code had the bug.

{‘m’:1}. And {‘n’:1}

**Comment by dengshaochun** [comment]
yeah, you are right,thank you, I've closed pull requests, and try to fix the problem.

**Comment by ponytailer** [comment]
yep, I created a PR for it. But the CI of this project has been down.

**Comment by ponytailer** [comment]
You can use the #185
