### ISSUE TITLE
the cache dosen't distinguish the request method for the same url?

### ISSUE THREAD

**Issue by axiaoxin** [thadeusb/flask-cache#183]
if there is a view like

    @app.route('/', methods=['GET', 'POST'])
    @cache.cached(timeout=10)
    def t():
        if request.method == GET:
              return "GET"
        else:
              return "POST"

the flask_cache get the same result both GET and POST in the cached time

**Comment by ponytailer** [comment]
The function `cached` is cached by parameters, so you can write it like this:

```
@app.route('/', methods=['GET', 'POST'])
def t():
    @cache.cached(timeout=10)
    def result(method)
        return "GET" if method == "GET" else "POST"
    return result(request.method)
```
