### ISSUE TITLE
Add a method to force a cache refresh

### ISSUE THREAD

**Issue by LeonB** [thadeusb/flask-cache#19]
For example, if you have very expensive methods I want to refresh the cache for them with a cronjob or maybe somewhere else in my code. I want to pre populate the cache to avoid a "thundering herd" or "cache miss storm".

It would be nice to have a convenient method to pre populating the cache.

**Comment by thadeusb** [comment]
Probably the easiest way is to just call your function. Need more details on your exact use case to suggest anything different.
