### ISSUE TITLE
import jinja2ext from flask.ext or flask_jinja2ext instead of flaskext

### ISSUE THREAD

**Issue by untitaker** [thadeusb/flask-cache#21]
I am not sure if i am right, since i am pretty new to flask, anyway, here goes...

```
    File "[...]/flask_cache/__init__.py", line 23, in [module]
    from flaskext.cache.jinja2ext import CacheExtension
    ImportError: No module named flaskext.cache.jinja2ext
```

looking into the sourcecode of flask itself, i found a notice saying that the flask.ext module provides a abstraction layer for loading flask extensions. It tries first flask_cache and at last flaskext.cache.

**Comment by thadeusb** [comment]
What version of Flask are you using? I can't seem to replicate it with Flask 0.9 in a fresh virtual environment.
