### ISSUE TITLE
NullCache for TESTING

### ISSUE THREAD

**Issue by klen** [thadeusb/flask-cache#23]
Why are you forced "cache.cache = NullCache()" for "TESTING=True"? I want to use "SimpleCache" for my test by example and etc.

It is always possible to setup CACHE_TYPE in test settings for your app (if you can set TESTING=True, you also can set CACHE_TYPE='null' if needed). But now it is useless with flask-cache for testing.

I have to set "TESTING=False" for my tests with your extension and its ugly by my opinion.

I propose to remove this condition.

**Comment by thadeusb** [comment]
Fixed in  commit 9988abf552

**Comment by Diaoul** [comment]
AFAIK [the documentation](https://pythonhosted.org/Flask-Cache/) hasn't been updated to reflect this. Please update.
