### ISSUE TITLE
PicklingError: Can't pickle <type 'function'>: attribute lookup __builtin__.function failed

### ISSUE THREAD

**Issue by guotie** [thadeusb/flask-cache#25]
when i use simple cache on windows, memoize got following error:

PicklingError: Can't pickle <type 'function'>: attribute lookup **builtin**.function failed

how to solve?

thanks.

**Comment by guotie** [comment]
I use memoize in BaseQuery's method

**Comment by thadeusb** [comment]
You cannot pickle functions or SQLAlchemy objects.
