### ISSUE TITLE
Multiple caches

### ISSUE THREAD

**Issue by explorigin** [thadeusb/flask-cache#26]
This is a wishlist item.  In my large application (currently built with other technologies, but I'm considering flask), I cache data to memory (simple), memcached and as a file.  it would be great if I could create 3 instances of cache, where each one could handle different scenarios.  But it seems like the current version can only handle one instance because it only reads config from the app.  This feels like a big limitation in an otherwise nice piece of software.

Thanks

**Comment by thadeusb** [comment]
What would you imagine the config file looking like?

**Comment by explorigin** [comment]
There are two options:
1) Give an alternate method to configure an instance:

```
ram_cache = Cache(config = [SIMPLE CACHE CONFIG DICT])
```

2) Provide separate instances within a cache.  Instantiation code would be the same, but config would look like:

```
CACHES = {
    'ram' : {
        'TYPE' : 'simple',
    },
    'memcache' : {
        'TYPE" : 'memcached',
        [further config options for memcache server
    }
}
```

Then you would reference the instance like:
cache.ram.cached()

I prefer #1 since it's cleaner and more Pythonic.

**Comment by thadeusb** [comment]
Method 1 it is, please check it out.

**Comment by explorigin** [comment]
AWESOME!  Many thanks!  If you ever find yourself in Tulsa, Oklahoma, I'll buy you a beverage of your choice.
