### ISSUE TITLE
Version 0.7.0 broke setup file.

### ISSUE THREAD

**Issue by klen** [thadeusb/flask-cache#29]
Last version of your module haves "import **version**" from flaskext.cache.

Also flaskext.cache haves another imports (like as: flask, werkzeug). Its realy broke installation of Flask-Cache. Because python setuptools try to read "install_requires" and get exception "No module named werkzeug".

In my case, Im have  have "requirements.txt" file:

```
Flask>=0.9
Flask-SQLAlchemy>=0.16
Flask-Cache>=0.6.0
```

And when I create virtualenv and try to do "pip install -r requirements.txt", its make exception.

Would you like fix that?

**Comment by huntrax11** [comment]
I got the same problem, and I think this commit 4cbc199db7651dcca103c1893f50b59ac3fa34c5 makes it happen.
And to avoid this kind of mistake, you'd better use CI tools like [Travis CI](http://travis-ci.org/)

**Comment by thadeusb** [comment]
Sorry about that, will fix it and push to pypi as soon as I have time available. Sometimes I forget and run the tests inside of my virtualenv and didn't catch this problem.

**Comment by thadeusb** [comment]
Should be fixed in 82a479a1850086017a63cfaadf865424b83b74a5

**Comment by huntrax11** [comment]
Thanks, and It works-

**Comment by klen** [comment]
Thanks!
