### ISSUE TITLE
username/password options

### ISSUE THREAD

**Issue by 1xch** [thadeusb/flask-cache#32]
I'm using a memcached server (on Heroku) and configuring username/password options WITHIN flask-cache to interface with a memcached server requiring that username/password be specified is not clear from the documentation.

I'm guessing this would go in CACHE_ARGS or CACHE_OPTIONS, but again how to do this isn't clear.  I'm sure it is simple, but a guide for someone not intimately acquainted with this code base would be useful. 

I can try a few things, and will gladly contribute, but clearer documentation/examples/saying this is or isn't possible would be appreciated.

**Comment by thadeusb** [comment]
Memcache does not have any authentication mechanisms built into it. You must install and configure memcached using a protocol wrapper called SASL that wraps authentication around connections in a protocol agnostic way.

http://code.google.com/p/memcached/wiki/SASLHowto

**Comment by 1xch** [comment]
You did not respond to my issue.

Perhaps the nature of my understanding is unclear at this point on technical details beyond my current level of knowledge, however the fact remains that to use memcached I've needed use something such as this (along custom functions and decorators) in a very small, custom use of memcached with a flask application:

```
cache = pylibmc.Client(
    servers=[os.environ.get('MEMCACHE_SERVERS')],
    username=os.environ.get('MEMCACHE_USERNAME'),
    password=os.environ.get('MEMCACHE_PASSWORD'),
    binary=True
)
```

which I'd prefer to not have to maintain custom cache functions for larger flask projects and use flask-cache, but if I need to do additional hoops, or still maintain the effort of rolling my own cache solution, then flask-cache will not be useful to me in the future in environments where I need to manage user/pass for caching

**Comment by untitaker** [comment]
@thrisp He did. Memcached does not have an authentication system, therefore his memcached support is technically complete even if he doesn't have support for sasl.

**Comment by untitaker** [comment]
I think this a hard one since `werkzeug.contrib.cache.MemcachedCache` doesn't seem to implement any auth systems either.

**Comment by thadeusb** [comment]
@thrisp 

Please check out the SASL branch on 323edd303fafa67b2ee34d8cbedfb37da5552526

Can you please test this and see if it works for you?

**Comment by 1xch** [comment]
Just saw this update, I am going to try this.

**Comment by thadeusb** [comment]
@thrisp Did it work for you? If so I will merge into master and release.

**Comment by allanlei** [comment]
@thadeusb I tried the SASL branch you suggested on Heroku with the Memcachier addon.  Seems to be working so far.
