### ISSUE TITLE
memoize cache key NOT unique

### ISSUE THREAD

**Issue by 1xch** [thadeusb/flask-cache#42]
I have a method:

```
@property
@cache.memoize(10)
def simple_stat(self):
    return dict({'viewed': self.viewed_all,
                         'presented': self.presented,
                         'submitted': self.submitted,
                         'completed': self.completed,
                         'edited': self.edited})
```

The expectation is that cache.memoize would make a key based on id(self) that is unique, even if the function has no arguments other than self.

Instead it is not -- at this point I get 1 cached simple_stat for all objects that have simple_stat method. If I pull them up in a dictionary or list, they all have the same simple_stat result where they should not. I am having difficulty working out a way to assign a unique key, and I'll be upfront about not 100% understanding the code I looked over here for making cache_keys. Making a callable function that creates a random key seems to serve no purpose(it would create a random key every time?) and I cannot pass in something like 'self.identifier' with the argument list.  If it a bug, reported. If there is something I do not understand, let me know.

**Comment by thadeusb** [comment]
Can you create a unit test or executable snipped of code that exhibits this bug then we can fix it.

**Comment by 1xch** [comment]
My testing skills are really basic, and providing an example would take a chunk of time, but I think the test could go something like this:

```
 def test_10c_a_classfunc_memoize(self):
        class Adder(object):
            def __init__(self, initial):
                self.initial = initial

           @property
           def calculated_value(self):
               return self.initial + 253 

            @property
            @self.cache.memoize(10)
            def add(self):
                return self.initial + self.calculated_value

        adder1 = Adder(1)
        adder2 = Adder(2)

        x = adder1.add                                                 # 254
        assert adder1.add == x                                  # 254 == 254
        assert adder1(3).add != x                              # 256 != 254
        assert adder1(4).add != adder2(5).add      # 257 != 258
```

Let me see if I can learn a bit more about testing and make this work.

**Comment by 1xch** [comment]
This passes:

```
def test_10c_a_classfunc_memoize(self):
        class Adder(object):
            def __init__(self, initial, plusi):
                self.initial = initial
                self.plusi = plusi

            @property
            def calculated_value(self):
                return self.plusi+2 

            @property
            @self.cache.memoize(10)
            def add(self):
                return self.initial + self.calculated_value

        adder1 = Adder(1, 2)
        adder2 = Adder(2, 4)

        x = adder1.add                                
        assert adder1.add == x                         
        assert Adder(1, 3).add != x                          
        assert adder1.add != adder2.add
```

So, I don't know. In my code, In an sqlalchemy model method (the one listed originally above), memoize only registers it once, and then spits that one time back no matter what instance it is called on. Any suggestions appreciated.

**Comment by 1xch** [comment]
hmmm. Just running through everything, I saw that the package I was using was way out of date(0.7.1). So there is that, and that seems to be the issue. The embarrassment is mine.
