### ISSUE TITLE
Invalid key in memoize

### ISSUE THREAD

**Issue by juhamust** [thadeusb/flask-cache#5]
Using memoize (at least with GAEMemcached) gives following error:

```
File "/home/user/project/x/src/packages/werkzeug/contrib/cache.py", line 313, in get
if _test_memcached_key(key):
TypeError: expected string or buffer
```

The root cause seems to be the tuple key type, while it expects to get a string.
I patched it locally as follows and it seems work ok:

``` python
        def memoize(f):
            @wraps(f)
            def decorated_function(*args, **kwargs):
                cache_key = ('memoize', f.__name__, id(f), args, str(kwargs))

                # PATCH: Create a string presentation of the key
                cache_key = '%s%s%s%s' % (cache_key[0], cache_key[1], cache_key[3], cache_key[4])
```

Used versions:
- Werkzeug: 0.6.2
- Flask-Cache: 0.3.2

**Comment by juhamust** [comment]
I'd also vote for certain naming convention for the cache key - so that it can be deleted with specified key name. Like:

```
memoize_<funcname>_<param1>_<param2>_<key1=val1>_<key2=val> 
```

instead what you're getting with the patch above.

As a related note, I'd like to see a function for deleting all the memoized keys since running the delete_memoized without key names does not seem to do that.

**Comment by juhamust** [comment]
Seems that the issue is already been addressed with latest changes. Keeping this still open as a notification to repository author.

As for the naming convention, see pull request #7

**Comment by thadeusb** [comment]
Thank you, I will be releasing 0.3.3 tonight.
