### ISSUE TITLE
delete_memoized does not delete all keys associated to the function

### ISSUE THREAD

**Issue by phacops** [thadeusb/flask-cache#50]
Hi,

I'm using memoize to store in cache the result of a static method in memcache. And when using delete_memoized, the cache is not delete as intended.

My object + function looks like this:

```
class User(UserMixin):
    @staticmethod
    @cache.memoize(30)
    def get(id):
        return 'Some info about the user'
```

I use it to do something like this:

```
User.get(user_id)
```

where user_id is an int.

When I update user's info, I want to delete the memoized info:

```
def some_action():
    cache.delete_memoized(User.get, current_user.id)
```

But the cache is never deleted (I'm checking with a memcached-tool dump). I checked it was the same id, same function_namespace.

I think the cache regarding this object should be deleted.

**Comment by thadeusb** [comment]
Can you make a unit test fail this?

The unit test 8,9,10 etc all pass the test to delete the cache.

Or are you referring to the version hash that is used to compute the cache? I will add a function to delete the version hash at least, however there it up to the application to make sure all possible cache keys made with this version hash have either been deleted, or have a timeout.

**Comment by thadeusb** [comment]
commit 71b0dc764250aaa6fd4d11545fcd0fa6760d1a27
