### ISSUE TITLE
Can't have more then 1 instance of Cache() in latest versions

### ISSUE THREAD

**Issue by rubensayshi** [thadeusb/flask-cache#53]
because `_set_cache` sets `app.extensions['cache']` and uses that for accessing the cache too it's not possible to have multiple instances of Cache() (eg. one local in-memory cache, one redis cache, one memcache cache).

in v0.8.0 this was still possible ...

**Comment by thadeusb** [comment]
https://github.com/thadeusb/flask-cache/commit/40da5f3a0278a4d231217e0210700e6777ccfaec

I do not think it is right to use app.extensions in this case.. plus why would there be multiple app instances running off of the same cache object? Any objections on reverting back to self.cache = cache_obj?

**Comment by untitaker** [comment]
But then you can't have multiple apps registered on one cache object...

**Comment by rubensayshi** [comment]
why? you can still set the cache object on the apps ..

**Comment by untitaker** [comment]
I meant regarding @thadeusb's suggestion to attach the cache directly to the Cache class.

**Comment by rubensayshi** [comment]
yea that doesnt fix anything xD

**Comment by thadeusb** [comment]
commit 31e0d3a648a1ebf3a83c7cd90fd606483308f0f3 fixes this, should go out in the next version.
