### ISSUE TITLE
Spread value among multiple keys ?

### ISSUE THREAD

**Issue by Carreau** [thadeusb/flask-cache#55]
Hi, 

I came across the issue that by default, Memcached does not support value > 1M. Which should be configurable, but in PAAS like heroku, you can't always do that. 

It's pretty easy [to circumvent](http://stackoverflow.com/questions/9127982/avoiding-memcache-1m-limit-of-values), so I was wondering is such an option would make sens in flask cache (or does it belong more in werkzeug contrib maybe ?)

I guess it comes with a performance cost of course...

I did it for my app, if you think this is a good idea, I can try to issue a PR if you wish .

Anyway, sorry if I missed anything obvious.

**Comment by untitaker** [comment]
This definetly should be implemented as a new cache backend in Werkzeug. Maybe one that inherits from the normal memcached one.
