### ISSUE TITLE
Upload py3k compatible version on PyPi

### ISSUE THREAD

**Issue by tlaundal** [thadeusb/flask-cache#72]
I'd love if you would upload the Python 3 compatible version to PyPi. The version that is there won't install on my system, but the github version will. 
If you don't think the package is ready yet, you could always upload it with "Development Status :: 3 - Alpha"

**Comment by bastianh** [comment]
yes... please.

**Comment by k4nar** [comment]
Still not on PyPi :'( .

**Comment by opalmer** [comment]
+1 I wouldn't mind installing from the from the github repo but the last travis build was 4 months ago and the last passing build was ~8 months ago (same time as the last release).  It's a great package for Python 2.x but I've love to see similar support for 3.x too.

**Comment by lyschoening** [comment]
+1
