### ISSUE TITLE
Set Timeout at Runtime

### ISSUE THREAD

**Issue by n0wa11** [thadeusb/flask-cache#77]
It will be nice to allow to set a different `timeout`, after the function is called.

```
cache_timeout
    The cache timeout value for this function. 
    For a custom value to take affect, this must be set before the function is called.
```

**Comment by n0wa11** [comment]
More precisely. Probably need to have the `timeout` argument attached to each cache, instead of a function.

**Comment by thadeusb** [comment]
Timeout is sent with the set request to the cache back end. So timeout gets
set automatically when the function is called. redis does allow setting
timeout after setting a value. I would like to keep the library as back end
agnostic as possible. It is possible to grab the cache key of the function
and set timeout on the cache back end for that specific key

**Comment by n0wa11** [comment]
Ok. Thanks.
