### ISSUE TITLE
Pip version of Flask-Cache not compatible with python3

### ISSUE THREAD

**Issue by exaroth** [thadeusb/flask-cache#87]
I'm not sure if this project is still maintained but when i tried using pip'ed version under python 3.4 it returned error 

```
No module named exceptions
```

probably related to fact that python 3 doesn't have it, Github version is working OK though.

**Comment by untitaker** [comment]
:+1:, please release a new version.

**Comment by fgimian** [comment]
+1 please :smile:

**Comment by Nassty** [comment]
bump!

**Comment by brutasse** [comment]
Dupe of #72. And #88 is related.

That said, big +1 from me as well.
